### ISSUE TITLE
Switch to new admin checklist

### ISSUE THREAD

**Issue by jonathan-s** [thegreenwebfoundation/greenwebfoundation-admin#40]
- [ ] Double check that permissions are correct for each group. Hostingproviders should only see certain things. 
- [x] Check that mail works correctly.
- [x] Once domain has been changed, send out email that says that they should reset password.
- [ ] Anything else?

**Comment by jonathan-s** [comment]
We've made the switch so this issue can be closed.
